config/routes.rb
Tclone::Application.routes.draw do
  root to: "users#index"
  resources :tweets
  post "follower_connections/create"
  delete "follower_connections/destroy"
  get "users/index"
  get "users/show"
  devise_for :users, path: "/", controllers: { registrations: "registrations" }
  get "/search", to: "user_queries#index"
  post "/favorite", to: "favorite_tweets#create"
  delete "/unfavorite", to: "favorite_tweets#destroy"
  get "/:username", to: "tweets#index", as: :user_tweets
  get "/:username/following", to: "follower_connections#following", as: :following
  get "/:username/followers", to: "follower_connections#followers", as: :followers

end

app/models/favorite_tweet.rb
class FavoriteTweet < ActiveRecord::Base
  belongs_to :user
  belongs_to :tweet
end

app/models/follower_connection.rb
class FollowerConnection < ActiveRecord::Base
  belongs_to :user
  belongs_to :follower, class_name: "User"
end

app/models/gravatar_url_generator.rb
class GravatarUrlGenerator
  def self.create_url(email_address)
    "https://secure.gravatar.com/avatar/#{gravatar_id(email_address)}"
  end
  def self.gravatar_id(email_address)
    Digest::MD5::hexdigest(email_address.downcase)
  end
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  belongs_to :user
  validates :user_id, :text, presence: true
  validates :text, length: { maximum: 140 }
  attr_accessible :user_id, :text

  scope :descending_order, ->(ids) { where(user_id: ids).order("created_at DESC") }

  before_create :parse_for_mentions

  def owner_name
    user.user_name
  end

  def owner_image
    user.gravatar_url
  end

  def parse_for_mentions
    self.text = TweetParser.new(self).parse
  end
end

app/models/tweet_parser.rb
class TweetParser
  attr_reader :tweet, :text
  def initialize(tweet)
    @tweet = tweet
    @text = tweet.text
  end

  def parse
    substitute_mentions_for_links
    send_mention_emails
    text
  end

  def send_mention_emails
    parsed_user_names.each do |user_name|
      MentionMailer.mention_email(tweet, user_name[1..-1])
    end
  end

  def substitute_mentions_for_links
    parsed_user_names.each do |user_name|
      text.gsub!(user_name, make_link(user_name))
    end
  end

  def make_link(user_name)
    "<a href='/#{user_name[1..-1]}' class='mention-link'>#{user_name}</a>"
  end

  def parsed_user_names
    @parsed_user_names ||= text.scan(/@{1}[a-zA-Z1-9_]+/i).flatten
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :follower_connections
  has_many :followers, through: :follower_connections

  has_many :following_connections, :class_name => "FollowerConnection", :foreign_key => "follower_id"
  has_many :following, :through => :following_connections, :source => :user
  attr_accessible :follower_id, :user_id

  has_many :tweets

  has_many :favorite_tweets
  has_many :favorites, through: :favorite_tweets, source: :tweet

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable

  attr_accessible :user_name, :email, :password, :password_confirmation, :remember_me
  attr_accessible :info
  validates :user_name, uniqueness: true
  validates :user_name, presence: true
  validates :user_name, length: { in: 3..20 }
  validates :info, length: { maximum: 140 }

  before_create :set_gravatar_url

  def following_tweets
    ids = following.map(&:id) << id
    Tweet.descending_order ids
  end

  def following?(user)
    following.include?(user)
  end

  def follow(user_id)
    user_to_follow = User.find_by_id(user_id)
    following << user_to_follow
  end

  def unfollow(user_id)
    following_connections.where(follower_id: id, user_id: user_id).first.destroy
  end

  def favorited?(tweet)
    favorites.include? tweet
  end

  def favorite_tweet(tweet_id)
    tweet = Tweet.find_by_id(tweet_id)
    favorites << tweet
  end

  def unfavorite(tweet_id)
    favorite_tweets.where(tweet_id: tweet_id, user_id: id).first.destroy
  end

  def publish_tweet(params)
    tweets.new(params)
    save
  end

  # Public: Find the amount of followers a user has, or the amount of users he
  # is following
  #
  # Examples
  #
  #   user.followers_count
  #   # => 4
  #
  #   user.following_count
  #   # => 2
  #
  #   user.tweets_count
  #   # => 3
  #
  # Returns an integer
  [:tweets, :followers, :following].each do |meth|
    define_method "#{meth}_count" do
      public_send(meth).count
    end
  end

  private
  def set_gravatar_url
    self.gravatar_url = GravatarUrlGenerator.create_url(email)
  end
end

app/models/user_query.rb
class UserQuery
  attr_reader :user_name
  def initialize(user_name)
    @user_name = user_name
  end

  def search
    User.where("user_name LIKE ?", "%#{user_name}%")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  def not_found
    raise ActionController::RoutingError.new('Not Found')
  end
end

app/controllers/favorite_tweets_controller.rb
class FavoriteTweetsController < ApplicationController
  before_filter :authenticate_user!
  def create
    current_user.favorite_tweet(params[:tweet_id])
    current_user.save
    render nothing: true
  end

  def destroy
    current_user.unfavorite(params[:tweet_id])
    current_user.save
    render nothing: true
  end
end

app/controllers/follower_connections_controller.rb
class FollowerConnectionsController < ApplicationController
  before_filter :authenticate_user!, :except => :index
  def following
    @user = User.find_by_user_name(params[:username]) || not_found
    @following_connections = @user.following
    render "connections"
  end

  def followers
    @user = User.find_by_user_name(params[:username])
    @following_connections = @user.followers
    render "connections"
  end

  def create
    current_user.follow(params[:user_id])
    current_user.save
    render nothing: true
  end

  def destroy
    current_user.unfollow(params[:user_id])
    current_user.save
    render nothing: true
  end
end

app/controllers/follower_connections_controller_controller.rb
class FollowerConnectionsControllerController < ApplicationController
  before_filter :authenticate_user!
  def create
    @following = current_user.followers.build(follower_id: params[:follower_id])
    if @following.save
      flash[:success] = "Followed #{params[:username]}!"
    else
      flash[:error] = "Error occurred! Follow again later."
    end
    redirect_to root_path
  end

  def destroy
    current_user.unfollow_user(params[:user])
    flash[:success] = "No longer following #{params[:username]}!"
    redirect_to root_path
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  def create
    flash[:notice] = "Check for your confirmation email to activate your account"
    super
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_filter :authenticate_user!, :except => :index

  def index
    @user = User.find_by_user_name(params[:username]) || not_found
    @tweets = Tweet.descending_order @user.id
  end

  def new
    @tweet = current_user.tweets.new
  end

  def create
    respond_to do |format|
      if current_user.publish_tweet(params[:tweet])
        flash[:tweet_success] = "Tweet successfully posted"
      else
        flash[:tweet_failure] = "Tweet failed to post"
      end
      format.js
    end
  end

  def destroy
    current_user.tweets.find(params[:id]).destroy
    flash[:notice] = "Tweet deleted"
  rescue
    flash[:failure] = "Delete failed"
  ensure
    redirect_to user_tweets_path(current_user.user_name)
  end
end

app/controllers/user_queries_controller.rb
class UserQueriesController < ApplicationController
  def index
    @users = UserQuery.new(params[:user_name]).search
    if @users.count == 1
      redirect_to user_tweets_path @users.first.user_name
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    if user_signed_in?
      @users = User.where("users.id <> ?", current_user.id)
      @following_tweets = current_user.following_tweets
    else
      redirect_to new_user_registration_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/follower_connections_controller_helper.rb
module FollowerConnectionsControllerHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/follower_connections/connections.html.erb
<div class="row">

  <%= render "users/user_stats", user: @user %>

<div class="span9">
  <div class="row">
    <div class="span6">
      <h1><%= @user.user_name %>'s tweets</h1>
    </div>
    <div class="span3">
      <% if @user != current_user %>
        <% if current_user.following?(@user) %>
          <%= link_to "Unfollow", follower_connections_destroy_path(:user_id => @user), :method => :delete, class: "btn btn-danger pull-right" %>
        <% else %>
          <%= link_to "Follow", follower_connections_create_path(:user_id => @user), :method => :post, class: "btn btn-primary pull-right" %>
        <% end %>
      <% end %>
    </div>
  </div>
  <% if @following_connections.present? %>
    <% @following_connections.each do |user| %>
      <%= render "users/user_info", user: user %>
    <% end %>
  <% else %>
    <p>Empty!</p>
  <% end %>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tclone</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <%= link_to "Twabbler", root_path, class: "brand" %>
        <div class="nav-collapse">
        <ul class="nav">
        <% if user_signed_in? %>
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Your Tweets", user_tweets_path(current_user.user_name) %></li>
          <li><%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %></li>
          <li><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link' %></li>
          <%= link_to "post a tweet", "#tweetModal", role: "button", data: {toggle: "modal"}, class: "btn btn-primary" %>
        <% else %>
          <li><%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link' %></li>
          <li><%= link_to "Login", new_user_session_path, :class => 'navbar-link' %></li>
        <% end %>
        </ul>
        <div class="pull-right">
          <%= form_tag search_path, method: :get do %>
            <%= text_field_tag :user_name, params[:user_name], class: 'user-search' %>
            <%= submit_tag "Search" %>
          <% end %>
        </div>
        </div>
      </div>
    </div>
  </div>
<div class="container">
  <% if flash[:notice] %>
    <p class="success"><%= flash[:notice] %></p>
  <% end %>
  <% if flash[:error] %>
    <p class="error"><%= flash[:error] %></p>
  <% end %>

  <%= yield %>
</div>

<!-- Modal -->
<div id="tweetModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <%= render "tweets/new" %>
</div>
</body>
</html>

app/views/shared/_follow_buttons.html.erb
<% if user_signed_in? && current_user != user %>
  <% if current_user.following?(user) %>
    <button type="button" data-id="<%= user.id %>" class="btn btn-danger pull-right unfollow" >Unfollow</button>
  <% else %>
    <button type="button" data-id="<%= user.id %>" class="btn btn-primary pull-right follow" >Follow</button>
  <% end %>
<% end %>

app/views/tweets/_new.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
  <h3 id="myModalLabel">Tweet</h3>
</div>
<%= form_for(Tweet.new, remote: true) do |f| %>
<div class="modal-body">
  <%= f.text_area :text %>
</div>
<div class="modal-footer">
  <p class="pull-left char-count">140</p>
  <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
  <%= f.submit "Tweet!", class: "btn btn-primary create-tweet" %>
</div>
<% end %>

app/views/tweets/_tweet.html.erb
<div class="row tweet">
  <div class="user_name span8">
    <%= link_to (image_tag(tweet.owner_image, alt: tweet.owner_name, class: "pull-left tweet-gravatar")), user_tweets_path(tweet.owner_name) %>
    <span class="pull-right"><%= time_ago_in_words(tweet.created_at) %></span>
    <%= link_to tweet.owner_name, user_tweets_path(tweet.owner_name) %>
    <div><%= tweet.text.html_safe %></div>
    <% if user_signed_in? %>
      <% if current_user.favorited? tweet %>
        <button type="button" class="btn btn-danger unfavorite" data-id="<%= tweet.id %>">Unfavorite</button>
      <% else %>
        <button type="button" class="btn btn-primary favorite" data-id="<%= tweet.id %>">Favorite</button>
      <% end %>
    <% end %>
    <% if @user == current_user && current_page?(user_tweets_path) %>
      <%= link_to "delete tweet", tweet, :method => :delete, class: "btn btn-danger pull-right" %>
    <% end %>
  </div>
</div>

app/views/tweets/create.js.erb
$("#tweetModal").modal("toggle")
$("#tweet_text").val("")
$(".container").eq(1).prepend("<p class='<%= flash[:tweet_success] ? "success" : "failure" %>'><%= flash[:tweet_success] or flash[:tweet_failure] %></p>")

app/views/tweets/index.html.erb
<div class="row">
  <%= render "users/user_stats", user: @user %>
  <div class="span9">
    <div class="row">
      <div class="span6">
        <h1><%= @user.user_name %>'s tweets</h1>
      </div>
      <div class="span3">
        <%= render "shared/follow_buttons", user: @user %>
      </div>
    </div>
    <% if @tweets.present? %>
      <% @tweets.each do |tweet| %>
        <%= render "tweets/tweet", tweet: tweet %>
      <% end %>
    <% else %>
      <p>No tweets!</p>
    <% end %>
  </div>
</div>

app/views/tweets/new.html.erb
<h2>Write a tweet</h2>
<%= form_for @tweet do |f| %>

  <div><%= f.label :text %><br />
    <%= f.text_area :text %>

  <div><%= f.submit "Tweet!" %></div>
<% end %>

app/views/user_queries/index.html.erb
<% if @users && @users.length > 0 %>
<% @users.each do |user| %>
  <%= render "users/user_info", user: user %>
<% end %>
<% else %>
  <h1>No users found!</h1>
<% end %>

app/views/users/_user_info.html.erb
<div class="row tweet">
  <div class="user_name span8">
    <%= link_to (image_tag(user.gravatar_url, alt: user.user_name, class: "gravatar")), user_tweets_path(user.user_name) %>
    <p><%= link_to "#{user.user_name}", user_tweets_path(user.user_name) %></p>
    <%= render "shared/follow_buttons", user: user %>
  </div>
</div>

app/views/users/_user_stats.html.erb
<div class="span3">
  <div class="row">
    <%= link_to (image_tag(user.gravatar_url, alt: user.user_name, class: "tweet-gravatar")), user_tweets_path(user.user_name) %>
    <p><%= user.user_name %></p>
  <ul class="unstyled">
    <li><%= link_to "Tweets: #{user.tweets_count}", user_tweets_path(user.user_name) %></li>
    <li><%= link_to "Followers: #{user.followers_count}", followers_path(user.user_name) %></li>
    <li><%= link_to "Following: #{user.following_count}", following_path(user.user_name) %></li>
  </ul>
  <% if @users && @users.length > 0 %>
    <p>here are the other users on the site:</p>
    <% @users.each do |user| %>
      <p><%= link_to "#{user.user_name}", user_tweets_path(user.user_name) %></p>
      <%= image_tag(user.gravatar_url, alt: user.user_name, class: "gravatar") %>
    <% end %>
  <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class="row">
  <%= render "users/user_stats", user: current_user %>

  <div class="span9">

    <% if @following_tweets.present? %>
      <% @following_tweets.each do |tweet| %>
        <%= render "tweets/tweet", tweet: tweet %>
      <% end %>
    <% else %>
      <p>you're not following anyone!</p>
    <% end %>

  </div>
</div>